# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpparma_hello_world <- function() {
    .Call(`_HVGR_rcpparma_hello_world`)
}

hvgedges <- function(xt) {
    .Call(`_HVGR_hvgedges`, xt)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_HVGR_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_HVGR_rcpparma_bothproducts`, x)
}

